### PR TITLE
Updating mbed-os to mbed-os-5.10.2

### PR DESCRIPTION
**Pull request by cmonr**
Please test this PR

If successful then merge, otherwise provide a known issue.
Once you get notification of the release being made public then tag Master with mbed-os-5.10.2 .

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
retest

**Comment by k-stachowiak** [comment]
retest

**Comment by k-stachowiak** [comment]
retest

**Comment by k-stachowiak** [comment]
Merging with known issues:
* #138 (Memory allocation failure in benchmark example IAR + KW24D)
* #208 (Benchmark example times out on UBLOX EVK ODIN W2, on GCC_ARM)
* #209 (No network interface found in the CI for UBLOX EVK ODIN W2)

**Pull request merged**
