### PR TITLE
Updating mbed-os to mbed-os-5.10.1

### PR DESCRIPTION
**Pull request by cmonr**
Please test this PR

If successful then merge, otherwise provide a known issue.
Once you get notification of the release being made public then tag Master with mbed-os-5.10.1 .

### CODE REVIEW

**Comment by sbutcher-arm** [comment]
retest

**Comment by sbutcher-arm** [comment]
CI is failing only on platforms which are known to fail. Therefore approving this PR for merge.

**Comment by cmonr** [comment]
@sbutcher-arm Sorry for butting in, but I came across this in my inbox.

If the devices are known to fail, is there a reason they're still a part of CI? Shouldn't they be removed until they're fixed/corrected?

**Comment by sbutcher-arm** [comment]
The failures are due to Mbed OS issue [#6545](https://github.com/ARMmbed/mbed-os/issues/6545) which is actively being worked on, and are a known issue.

**Pull request merged**
