### PR TITLE
Authcrypt - stop using \r\n and use just \n

### PR DESCRIPTION
**Pull request by JanneKiiskila**
There is a fix via small `mbed_app.json` trick to get the proper C-style
linechanges working.

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
@andresag01 @k-stachowiak

**Comment by JanneKiiskila** [comment]
CI issues? 

```
[build-authcrypt-K64F-ARM] c:\jsbld\ws\mbed-os\e_g_pr_tls@4>rmdir /S /Q . 
[build-authcrypt-K64F-ARM] .\TLS-CL~2\DURABL~1\jenkins-log.txt - The process cannot access the file because it is being used by another process.
[build-authcrypt-K64F-ARM] The process cannot access the file because it is being used by another process.
[Pipeline] [build-authcrypt-K64F-ARM] checkout
[build-authcrypt-K64F-ARM] Cloning the remote Git repository
[build-authcrypt-K64F-ARM] Cloning repository git@github.com:ARMmbed/mbed-os-example-tls.git
[build-authcrypt-K64F-ARM] ERROR: Failed to clean the workspace
[build-authcrypt-K64F-ARM] java.nio.file.FileSystemException: c:\jsbld\ws\mbed-os\e_g_pr_tls@4\tls-client@tmp\durable-19ffe8a3\jenkins-log.txt: The process cannot access the file because it is being used by another process.
[build-authcrypt-K64F-ARM] 
```

**Comment by andresag01** [comment]
@JanneKiiskila: Thanks for the PR. I was unaware of that particular mbed OS configuration option and always relied on configuring the serial terminal. I think the PR is looking good (I have not fully reviewed it though). My only concern is that merging this as is also means that now the printing is not consistent throughout all the example apps.

**Comment by andresag01** [comment]
@JanneKiiskila: Indeed, there were some CI issues in the previous build that were not related to the change. I have triggered another build, but I do not think there will be any issues.

**Comment by JanneKiiskila** [comment]
I can do the rest of the apps under mbed-os-example-tls as well, it's trivial.

**Comment by JanneKiiskila** [comment]
Anyway, the printouts are consistent from end user point of view.

**Comment by AndrzejKurek** [comment]
The changes look ok, but having the problems with our CI - I'd like to rerun the testing.

**Comment by andresag01** [comment]
@JanneKiiskila: Thank you for your contribution! I wanted to make sure all the sample applications are consistent. Therefore, I created the PR https://github.com/ARMmbed/mbed-os-example-tls/pull/126 which is a superset of these changes. Therefore, I am closing this. I hope you do not mind...

**Pull request closed without merging**
