### PR TITLE
Do not merge - Update mbed os 5.10.0 with a stack fix

### PR DESCRIPTION
**Pull request by k-stachowiak**
This PR tests stack usages fixes from another PR with Mbed OS 5.10

### CODE REVIEW

**Comment by k-stachowiak** [comment]
retest

**Comment by andresag01** [comment]
This fails in the expected target KW14D with IAR and benchmark. Everything else seems OK.

**Comment by andresag01** [comment]
@k-stachowiak: Is this PR still necessary? Can we close it?

**Comment by k-stachowiak** [comment]
@andresag01 This PR is no longer necessary.

**Pull request closed without merging**
