### PR TITLE
Add skip to possible test outcomes

### PR DESCRIPTION
**Pull request by k-stachowiak**
This PR separates certain memory related errors from others and records respective tests as skipped rather than failed

### CODE REVIEW

**Comment by k-stachowiak** [comment]
retest

**Comment by k-stachowiak** [comment]
retest

**Comment by k-stachowiak** [comment]
retest

**Comment by andresag01** [comment]
@k-stachowiak: What is your plan for this PR? Will you continue development or should we close it?

**Comment by k-stachowiak** [comment]
@andresag01 I am not up to date regarding the heap allocation issues on more constrained devices. However, this PR makes as much sense as the idea of skipping tests upon heap allocation failure. Once the idea has been rejected, this PR may be closed.

**Comment by sbutcher-arm** [comment]
I appreciate what you're trying to do with this PR @k-stachowiak, by trying to make it work in all instances on all targets, but it's supposed to be an example program showing others how to use the API, and not just a test application, or one to show off performance. As such I think conditionally skipping steps because there isn't sufficient memory looks odd from the outside, and unnecessarily complicates the example. 

In my view, as I describe in #138, I think we should just disable the failing tests, or fix the underlying issue of available memory. 

Therefore I'd like to close this PR.

**Pull request closed without merging**
