### PR TITLE
Reduce MPI_MAX_SIZE parameter

### PR DESCRIPTION
**Pull request by k-stachowiak**
This PR test influence of a configuration change on the memory issues

### CODE REVIEW

**Comment by k-stachowiak** [comment]
retest

**Comment by k-stachowiak** [comment]
retest

**Comment by RonEld** [comment]
@k-stachowiak I think we can close this issue, since there is now a PR setting the size of `MBEDTLS_MPI_MAX_SIZE` to 512 by default in Mbed-OS, in https://github.com/ARMmbed/mbed-os/pull/8936

**Comment by k-stachowiak** [comment]
@RonEld I agree.

**Pull request closed without merging**
