### PR TITLE
add contributing file

### PR DESCRIPTION
**Pull request by 0xc0170**
Add license information to readme + contributing file

This follows Mbed OS contribution + license information.

Note: sending this to master, 5.12 release branch should also be updated

### CODE REVIEW

**Comment by Patater** [comment]
@0xc0170 Should we add a LICENSE file as well to this repo, as we did with https://github.com/ARMmbed/mbed-os-example-mbed-crypto/ ?

**Comment by 0xc0170** [comment]
+1 for the license file

This was left behind, I'll try to update it tomorrow , sorry for the delay

**Comment by 0xc0170** [comment]
LICENSE file added, lets merge this for 5.15

**Comment by 0xc0170** [comment]
@Patater can we merge this?

**Pull request merged**
