### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarceloSalazar**
- Tweak comments about easy-connect and configuring other network interfaces (https://github.com/ARMmbed/easy-connect/issues/60)
- Add pointer to troubleshooting doc

@sbutcher-arm @AnotherButler

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
Made changes as suggested.

**Comment by adbridge** [comment]
@mazimkhan @sbutcher-arm Can we get this merged please

**Comment by mazimkhan** [comment]
LGTM. @sbutcher-arm

**Comment by Patater** [comment]
Reviewed, approved, and merged (by hand).

**Pull request closed without merging**
